server:
  port: 9091
# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 169167866Spl.
    url: jdbc:mysql://localhost:3306/online_study?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
# 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# ip配置
ip: localhost

# 用户信息
user:
  default-avatar-name: defaultAvatar2.png

# jwt配置
jwt:
  # jwt开关
  flag: true

